import { getValidMoves, PIECE_STRENGTH } from "./pieces.js";
import { getRPSResult, FACTION } from "./board.js";
import { Hex } from "./hex.js";
import { isKingdomCheck } from "./game-check.js";
import {
  pickBookMove,
  buildOpeningBook,
  inBook,
  learnFromGame,
  getLearnedData,
  loadLearnedData,
} from "./opening-book.js";

// Import all core AI logic from shared module
import {
  TURN_ORDER,
  RPS_VALUE_MULTIPLIER,
  getDynamicPieceValue,
  getMaterialValue,
  calculateTimeBudget,
  MAX_DEPTH,
  TIME_LIMIT_MS,
  AI_PERSONALITIES,
  getPersonalityWeights,
  getPersonalityAggression,
  setPersonality,
  getPersonality,
  getPersonalities,
  boardHash,
  getPSTValue,
  evaluatePawnStructure,
  evaluateEndgame,
  evaluateBoard,
  getAllActions,
  getLegalMoves,
  legalMoveCheck,
  rebuildOccupiedMap,
  simulateMove,
  undoMove,
  minimax,
  quiesce,
  iterativeDeepening,
  greedyBestMove,
  calculateBestMove,
  setAIDepth,
  setAIPersonality,
  getAIPersonalities,
  deserializeGame,
  // Pondering
  startPondering,
  stopPondering,
  getPonderMove,
  isPondering,
  PonderState,
  setPonderProgressCallback,
  // SEE (Static Exchange Evaluation)
  SEE_PIECE_VALUES,
  getSeeValue,
  see,
  quickSee,
  // Search stats
  nodesSearched,
} from "./ai-core.js";

// Re-export for backward compatibility
export {
  TURN_ORDER,
  RPS_VALUE_MULTIPLIER,
  getDynamicPieceValue,
  getMaterialValue,
  calculateTimeBudget,
  MAX_DEPTH,
  TIME_LIMIT_MS,
  AI_PERSONALITIES,
  getPersonalityWeights,
  getPersonalityAggression,
  setPersonality,
  setAIPersonality,
  getPersonality,
  getPersonalities,
  getAIPersonalities,
  boardHash,
  getPSTValue,
  evaluatePawnStructure,
  evaluateEndgame,
  evaluateBoard,
  getAllActions,
  getLegalMoves,
  legalMoveCheck,
  rebuildOccupiedMap,
  simulateMove,
  undoMove,
  minimax,
  quiesce,
  iterativeDeepening,
  greedyBestMove,
  calculateBestMove,
  setAIDepth,
  deserializeGame,
  // Pondering
  startPondering,
  stopPondering,
  getPonderMove,
  isPondering,
  PonderState,
  setPonderProgressCallback,
  // SEE (Static Exchange Evaluation)
  SEE_PIECE_VALUES,
  getSeeValue,
  see,
  quickSee,
  // Search stats
  nodesSearched,
  // Opening book learning
  learnFromGame,
  getLearnedData,
  loadLearnedData,
};
